version: '2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: elastic
    restart: always
    environment:
      - http.host=0.0.0.0
      - network.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './elastic-data:/usr/share/elasticsearch/data'
    ports:
      - 9200:9200
  db:
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - './db-data:/var/run/mysqld'
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - './redis-data:/data'
    command: redis-server
    environment:
      REDIS_HOST: redis://127.0.0.1
      REDIS_DB: 0
      REDIS_PORT: 6379
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - '5673:5672'
      - '15673:15672'
    volumes:
      - './rabbitmq-data:/var/lib/rabbitmq'
    command: rabbitmq-server
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  app:
    build: .
    command: rails db:migrate && rails routes && rake sneakers:run WORKERS = MessageCreateWorker,ChatCreateWorker && rails s 
    volumes:
      - '.:/app'
    ports:
      - '3001:3000'
    depends_on:
      - elastic
      - rabbitmq
      - db
      - redis
    links:
      - db
      - elastic
    environment:
      REDIS_HOST: redis
      DB_USER: root
      DB_NAME: chatDB
      DB_PASSWORD: password
      DB_HOST: db
      REDIS_DB: 0
      REDIS_PORT: 6379
      RABBITMQ_DEFAULT_HOST: rabbitmq
      RABBITMQ_DEFAULT_PORT: 5672
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      ELASTICSEARCH_URL: elastic

